# Generated by Django 3.2.8 on 2021-10-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211014_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='cover',
        ),
    ]
