# Generated by Django 3.2.8 on 2021-10-14 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_place_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('commerce', 'Comercio'), ('donations', 'Doacoes'), ('colect', 'Coleta'), ('other', 'Outros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='core.Attachment'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, to='core.Bookmark'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='publication_comments', to='core.Comment'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='publication_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
