# Generated by Django 3.2.8 on 2021-10-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211014_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='place',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='publication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.publication'),
            preserve_default=False,
        ),
    ]
