# Generated by Django 3.2.8 on 2021-10-18 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20211018_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='core.Attachment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_comments', to='core.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('hint', 'Dica'), ('discussion', 'Discussão'), ('news', 'Notícia'), ('question', 'Pergunta'), ('other', 'Outros')], max_length=255),
        ),
    ]
